name: A+ Trade Scanner

on:
  schedule:
    - cron: "*/15 * * * *"   # 15 dakikada bir çalışır
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu çek
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Paketleri kur
      run: |
        pip install requests

    - name: Scanner çalıştır
      run: |
        python scanner.py
